### ISSUE TITLE
The bot spamming when private message is send

### ISSUE THREAD

**Issue by BambouVX** [kabirsingh2004/Mino-Discord-Bot#2]
![image](https://user-images.githubusercontent.com/51539303/192815737-b68b9bfb-553b-4068-bda0-058e74b2fc8e.png)
how to repare ?

**Comment by tatargod** [comment]
u fixed?

**Comment by mimio10** [comment]
meme soucis

**Comment by kabirsingh2004** [comment]
fixed now
